### ISSUE TITLE
You are leaking private data. 

### ISSUE THREAD

**Issue by Benwebdev** [bogdanmarin/artisan#1]
Ben Line here, remove this from your repo 

https://github.com/bogdanmarin/artisan/blob/master/config/secrets.js

serious security issue 

You should really get GitHub pro and place all your stuff in private repos. 

Thanks <3 

{{ BL }}

**Comment by bogdanmarin** [comment]
These are keys for testing only, not production so it's ok.

**Comment by Benwebdev** [comment]
Well, Its a little less serious now, just making you aware...
